// src/form-vue2/example/src/components/input.vue
<template>
  <div>
    <input
      type="text"
      v-model="fromData[prop]"
      :placeholder="label"
      @input="validator"
    />
    <p>{{result.valid || result.msg}}</p >
  </div>
</template>

<script>
export default {
  name: 'ViInput',
  props: {
    fromData: Object,
    prop: String,
    label: String,
    validator: Function,
    result: Object,
  },
}
</script>

// src/form-vue2/example/src/components/input.jsx
export const viInput = ({
  formData, formItem: {prop, label}, validator, result
}) => {
  return {
    // eslint-disable-next-line
    render(h) {
      return <ViInput
        fromData={formData}
        prop={prop}
        label={label}
        validator={validator}
        result={result}
      />
    }
  }
}

export const submit = ({ submit }) => {
  return {
    // eslint-disable-next-line
    render(h) {
      return <h2 onClick={submit}>submit</h2>
    }
  }
}
